export interface Mosque {
  _id?: string;  // Optional, as it's generated by MongoDB
  name: {
    en: string;
    ur: string;
  };
  location: {
    en: string;
    ur: string;
  };
  timings: {
    fajr: {
      en: string;
      ur: string;
    };
    dhuhr: {
      en: string;
      ur: string;
    };
    asr: {
      en: string;
      ur: string;
    };
    maghrib: {
      en: string;
      ur: string;
    };
    isha: {
      en: string;
      ur: string;
    };
    juma: {
      en: string;
      ur: string;
    };
  };
}