export interface Mosque {
    _id?: string; // Optional, as it's generated by MongoDB
    name: string;
    name_urdu: string;
    location: string;
    timings: {
      fajr: string;
      dhuhr: string;
      asr: string;
      maghrib: string;
      isha: string;
      juma: string;
    };
  }